import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavHeader } from '@/components/nav-header'
import { PlaylistList } from '@/components/playlist-list'
import { Footer } from '@/components/footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black h-full">
          <div className="p-2 grid grid-cols-layout grid-rows-layout gap-2 h-full">
            <section className="flex flex-col gap-2 h-full">
              <NavHeader />
              <PlaylistList />
            </section>
            <main>{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
