import type { Metadata } from 'next'
import '../globals.css'
import { Link } from '@/components/link'
import { HomeIcon, Library, Search } from 'lucide-react'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="p-2 grid grid-cols-layout gap-2">
      <div className="flex flex-col gap-2">
        <div className="bg-spotifyGray700 rounded-lg px-6 py-4 flex flex-col gap-1">
          <Link icon={HomeIcon} text="Home" />
          <Link icon={Search} text="Search" />
        </div>
        <div className="bg-spotifyGray700 rounded-lg px-6 py-4">
          <Link icon={Library} text="Sua biblioteca" />
        </div>
      </div>
      <div>{children}</div>
    </main>
  )
}
